name: Build mirror image

on:
    push:
        branches:
            - development

jobs:
    Build:
        name: Run on Ubuntu
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                go-version: '1.25'

            - name: Login to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PAT }}

            - name: Generate code
              run: make generate

            - name: Generate manifests
              run: make manifests

            - name: Build binary
              run: make build

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ghcr.io/${{ github.repository }}
                tags: |
                    type=sha,format=short
                    type=raw,value=dev

            - name: Build image (make)
              run: |
                echo "${{ steps.meta.outputs.tags }}" | while read -r tag; do
                    make docker-build IMG="$tag"
                done

            - name: Push images
              run: |
                echo "${{ steps.meta.outputs.tags }}" | while read -r tag; do
                    docker push "$tag"
                done
